// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// EmailService is an autogenerated mock type for the EmailService type
type EmailService struct {
	mock.Mock
}

// SendEmailToUser provides a mock function with given fields: from, userID, msg
func (_m *EmailService) SendEmailToUser(from string, userID uuid.UUID, msg []byte) error {
	ret := _m.Called(from, userID, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, []byte) error); ok {
		r0 = rf(from, userID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailService creates a new instance of EmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailService {
	mock := &EmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
